apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: production
  labels:
    app: harivelo
    component: backend
spec:
  selector:
    app: harivelo
    component: backend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  type: ClusterIP