apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: production
  labels:
    app: harivelo
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harivelo
      component: frontend
  template:
    metadata:
      labels:
        app: harivelo
        component: frontend
    spec:
      containers:
      - name: frontend
        image: 240676008744.dkr.ecr.eu-west-3.amazonaws.com/harivelo-app-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: regcred